# Generated by Django 3.0 on 2019-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_author', models.CharField(max_length=30)),
                ('article_post_time', models.DateTimeField(auto_now_add=True)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
