# Generated by Django 3.0 on 2019-12-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.CharField(max_length=50),
        ),
    ]
