# Generated by Django 3.0 on 2019-12-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0003_auto_20191216_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
