# Generated by Django 3.0 on 2019-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0004_auto_20191217_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_image',
            field=models.FileField(default=True, upload_to='uploads/author_images'),
        ),
    ]
