# Generated by Django 3.0 on 2019-12-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0005_post_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
