# Generated by Django 3.0 on 2020-01-19 22:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('soulofseattlepages', '0006_auto_20191221_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_biography',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
