# Generated by Django 2.2.9 on 2020-01-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0007_auto_20200119_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
