# Generated by Django 3.0 on 2020-02-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0008_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
