# Generated by Django 3.0 on 2020-02-14 07:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('soulofseattlepages', '0009_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_firstName', models.CharField(max_length=30)),
                ('author_lastName', models.CharField(max_length=30)),
                ('author_biography', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_Title', models.CharField(max_length=255, unique=True)),
                ('post_Slug', models.CharField(max_length=255, unique=True)),
                ('post_Content', models.TextField()),
                ('post_CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('post_UploadImage', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('post_Status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('post_Category', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soulofseattlepages.author')),
                ('post_Tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
