# Generated by Django 3.0 on 2020-02-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0010_author_userpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-post_CreatedOn']},
        ),
    ]
