# Generated by Django 3.0 on 2020-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0011_auto_20200214_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='post_Tags',
            new_name='tags',
        ),
    ]
