# Generated by Django 3.0 on 2020-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulofseattlepages', '0013_auto_20200214_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_Category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Politics', 'Politics'), ('Opinion', 'Opinion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Health', 'Health'), ('Tech', 'Tech')], default='Lifestyle', max_length=200),
        ),
    ]
